HEFENG_HOST1: "a"  # 替换为你的和风天气API主机地址1，设计为两个轮换使用，若只有一个可以填相同的
# HEFENG_HOST2: "b"  # 替换为你的和风天气API主机地址2（如果有的话，取消注释）
# 如果还有可以使用的API主机地址，可以继续添加 HEFENG_HOST3, HEFENG_HOST4 等
HEFENG_KEY1: "APIKEY1" # 替换为你的和风天气API密钥1，设计为两个轮换使用，若只有一个可以填相同的
# HEFENG_KEY2: "APIKEY2" # 替换为你的和风天气API密钥2（如果有的话，取消注释）
# 如果还有可以使用的API密钥，可以继续添加 HEFENG_KEY3, HEFENG_KEY4 等
times: 60 # 请求频率，单位为秒，和风天气免费API额度每分钟请求一次刚刚好
TURNSTILE_SECRET_KEY: "0x"  # 替换为你的 Cloudflare Turnstile Secret Key
TURNSTILE_SITE_KEY: "0x" # 替换成你自己的 Site Key
LOCATION_NAME: "广州"  # 替换为服务器所在地，用于前端展示
LOCATION_ID: 101280101  # 广东广州的和风天气位置ID
admin_username: techccy # 管理员登录账号
admin_password: "" # 管理员登录密码
force_rain_duration: 10   # 强制降雨持续时间（分钟）
totp_decrypt_password: "password" #用于加密管理员登录时二次验证器密钥的密码

# AI 内容审查配置
AI_MODERATION:
  API_KEY: "YOUR_API_KEY"
  BASE_URL: "YOUR_BASE_URL" 
  MODEL: "MODEL"
  SYSTEM_PROMPT: >
    你是一个内容审查助手。请分析用户提交的内容是否包含暴力、色情、政治敏感或人身攻击。
    如果内容违规，请只返回 "True"；
    如果内容安全，请只返回 "False"。
    不要返回任何其他文字。